import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
const poppins = Poppins({ subsets: ["latin"] ,weight:'400'});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}  bg-[#F8F8F8] text-[#1E1E1E] px-20 flex flex-col h-screen`}>
        <Navbar />
        <div className="flex-1">{children}</div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
